# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Area name')),
                ('location', models.CharField(max_length=60, verbose_name='Area location')),
                ('info', models.TextField(max_length=500, verbose_name='Area Information')),
                ('sqkm', models.IntegerField(verbose_name='Area Square meter')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Block name')),
                ('location', models.CharField(max_length=60, verbose_name='Block location')),
                ('info', models.TextField(max_length=500, verbose_name='Block Information')),
                ('sqkm', models.IntegerField(verbose_name='Block Square meter')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Cell name')),
                ('location', models.CharField(max_length=60, verbose_name='Cell location')),
                ('info', models.TextField(max_length=500, verbose_name='Cell Information')),
                ('sqm', models.IntegerField(verbose_name='Cell Square meter')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Block')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
